# Generated by Django 3.0.2 on 2020-01-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('polarity', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
